{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "elderscape-llm-chat",
  "main": "src/index.ts",
  "compatibility_date": "2025-10-26",
  "compatibility_flags": [
    "nodejs_compat",
    "global_fetch_strictly_public"
  ],
  "assets": {
    "binding": "ASSETS",
    "directory": "./public"
  },
  "observability": {
    "enabled": true
  },
  "ai": {
    "binding": "AI"
  },
  "ai_endpoints": [
    {
      "binding": "TEXT_TO_IMAGE",
      "model": "@cf/stable-diffusion-v1.5",
      "max_tokens": 2048
    }
  ],
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "elderscape-d1"
    }
  ],
  "kv_namespaces": [
    {
      "binding": "AI_MEMORY",
      "id": "8c5a2eb8be934b078487ae615c0de92e"
    }
  ],
  "upload_source_maps": true
}
