name = "elderscape"
main = "src/index.ts"
compatibility_date = "2025-10-01"

[dev]
local_protocol = "http"

[site]
bucket = "./public"
entry-point = "workers-site"

[vars]
HF_API_TOKEN = "<your-hf-api-token>"

[[kv_namespaces]]
binding = "AI_MEMORY"
id = "<your-kv-namespace-id>"

[[d1_databases]]
binding = "DB"
database_name = "elderscape-db"

[triggers]
crons = ["0 0 * * *"]
