name = "elderscape"
main = "src/index.ts"
compatibility_date = "2025-04-01"
type = "javascript"

[compatibility_flags]
flags = ["nodejs_compat", "global_fetch_strictly_public"]

# Static assets
[assets]
binding = "ASSETS"
directory = "./public"

# D1 database
[[d1_databases]]
binding = "DB"
database_name = "elderscape-db"

# KV for AI memory
[[kv_namespaces]]
binding = "AI_MEMORY"
id = "8c5a2eb8be934b078487ae615c0de92e"

# Cloudflare AI binding
[ai]
binding = "AI"

# Optional endpoints
[[ai_endpoints]]
binding = "HUGGINGFACE_GPT2"
model = "@cf/huggingface/gpt2"

upload_source_maps = true
